name: release

on:
  release:
    types:
      - created

jobs:
  build:
    name: build target
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        espidf_target:
          - esp32
          - esp32c3
          - esp32c6
          - esp32h2
          - esp32p4
          - esp32s2
          - esp32s3
        path:
          - 'blink-app'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Build Test Application with ESP-IDF
        uses: espressif/esp-idf-ci-action@v1.1.0
        with:
          esp_idf_version: "latest"
          target: ${{ matrix.espidf_target }}
          path: ${{ matrix.path }}
          command: |
            idf.py build &&
            cd build &&
            esptool.py --chip ${{ matrix.espidf_target }} merge_bin -o ${{ matrix.espidf_target }}-merged.bin "@flash_args"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.espidf_target }}-merged.bin
          path: ${{ matrix.path }}/build/${{ matrix.espidf_target }}-merged.bin
